'use client'

import React, { useEffect, useState } from 'react'
import { toast } from 'sonner'
import type { StrayAnimal } from './types'

interface Identification { id: string; type: string; number: string; date: string; operator: string; notes: string; animal?: { csvrNumber: string; species: string } }
interface Props { animals: StrayAnimal[]; onRefresh: () => void }
const input = 'w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm outline-none focus:border-purple-400 focus:ring-2 focus:ring-purple-100'
const types: Record<string, string> = { MICROCHIP: 'ميكروشيب', TAG: 'حلقة أذنية', COLLAR: 'طوق', TATTOO: 'وشم', OTHER: 'أخرى' }

export default function IdentificationsTab({ animals, onRefresh }: Props) {
  const [animalId, setAnimalId] = useState(animals[0]?.id || '')
  const [identifications, setIdentifications] = useState<Identification[]>([])
  const [saving, setSaving] = useState(false)
  const [form, setForm] = useState({ type: 'MICROCHIP', number: '', date: new Date().toISOString().slice(0, 10), operator: '', photo: '', notes: '' })
  useEffect(() => { if (!animalId && animals[0]) setAnimalId(animals[0].id) }, [animalId, animals])
  useEffect(() => { fetch(`/api/csvr/identifications${animalId ? `?animalId=${encodeURIComponent(animalId)}` : ''}`).then((response) => response.ok ? response.json() : { identifications: [] }).then((data) => setIdentifications(data.identifications || [])).catch(() => setIdentifications([])) }, [animalId])
  const submit = async (event: React.FormEvent) => {
    event.preventDefault(); if (!animalId || !form.number.trim()) { toast.error('اختر الحيوان وأدخل رقم التعريف'); return }
    setSaving(true)
    try { const response = await fetch('/api/csvr/identifications', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, animalId }) }); const data = await response.json().catch(() => ({})); if (!response.ok) { toast.error(data.error || 'تعذر التسجيل'); return }; toast.success('تم تسجيل التعريف وتحديث الحالة'); setForm({ ...form, number: '', photo: '', notes: '' }); const list = await fetch(`/api/csvr/identifications?animalId=${encodeURIComponent(animalId)}`).then((result) => result.ok ? result.json() : { identifications: [] }); setIdentifications(list.identifications || []); onRefresh() } catch { toast.error('حدث خطأ أثناء التسجيل') } finally { setSaving(false) }
  }
  return <div className="space-y-4"><div className="rounded-2xl bg-gradient-to-l from-purple-700 to-indigo-600 p-4 text-white shadow-lg"><h2 className="text-lg font-extrabold">🏷️ تعريف الحيوانات</h2><p className="mt-1 text-xs text-purple-50">تسجيل وسائل التعريف ومنع تكرار الرقم داخل السجل الوطني للقسم.</p></div>{animals.length === 0 ? <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-400">لا توجد حيوانات مسجلة.</div> : <><form onSubmit={submit} className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:grid-cols-2 lg:grid-cols-3"><select value={animalId} onChange={(event) => setAnimalId(event.target.value)} className={input}><option value="">اختر الحيوان</option>{animals.map((animal) => <option key={animal.id} value={animal.id}>{animal.csvrNumber} — {animal.species}</option>)}</select><select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })} className={input}>{Object.entries(types).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><input required placeholder="رقم التعريف *" value={form.number} onChange={(event) => setForm({ ...form, number: event.target.value })} className={input} /><input type="date" value={form.date} onChange={(event) => setForm({ ...form, date: event.target.value })} className={input} /><input placeholder="العون أو الطبيب" value={form.operator} onChange={(event) => setForm({ ...form, operator: event.target.value })} className={input} /><input placeholder="مرجع الصورة" value={form.photo} onChange={(event) => setForm({ ...form, photo: event.target.value })} className={input} /><textarea placeholder="ملاحظات" value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} rows={1} className={`${input} sm:col-span-2`} /><button disabled={saving} className="rounded-xl bg-purple-600 px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{saving ? 'جارٍ...' : 'تسجيل التعريف'}</button></form><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-4 py-3 text-sm font-bold text-slate-700">سجل التعريفات</div>{identifications.length === 0 ? <p className="p-8 text-center text-sm text-slate-400">لا توجد وسائل تعريف لهذا الحيوان.</p> : <div className="divide-y divide-slate-100">{identifications.map((item) => <div key={item.id} className="grid gap-1 px-4 py-3 text-xs sm:grid-cols-[120px_1fr_1fr_1fr]"><span className="text-slate-400">{new Date(item.date).toLocaleDateString('ar-MA')}</span><span className="font-bold text-purple-700">{types[item.type] || item.type}</span><span className="font-mono font-semibold text-slate-700">{item.number}</span><span className="text-slate-500">{item.operator || '—'}</span></div>)}</div>}</div></>}</div>
}
