'use client'

import React, { useEffect, useState } from 'react'
import { motion } from 'framer-motion'
import { toast } from 'sonner'
import { useAppStore } from '@/lib/store'
import { COMMUNE_LABELS, CSVR_CAPTURE_STATE_LABELS, CSVR_PRIORITY_LABELS } from '@/lib/constants'
import { RABIES_ROUTE_LABELS, RABIES_VACCINE_LABELS } from './rabies-vaccination'

interface Props { selectedCommune: string }
interface Shelter { name: string; address: string; capacity: number }
interface CsvrSettings {
  shelters: Shelter[]
  speciesTypes: string[]
  priorityLevels: string[]
  captureStates: string[]
  operational: { defaultPriority: string; responseTargetHours: number; quarantineDays: number; requireLocation: boolean; requirePhotoForClosure: boolean }
  contacts: { responsibleName: string; veterinaryService: string; emergencyPhone: string; email: string }
  notifications: { urgentAlerts: boolean; healthAlerts: boolean; missionReminders: boolean }
  vaccination: { preferredVaccineType: string; preferredRoute: string; protocolReference: string; requireMedicalValidation: boolean }
  workflow: { autoCreateUrgentMission: boolean; followUpAfterDays: number; lockClosedRecords: boolean; allowStatusReopen: boolean }
  map: { defaultZoom: number; showBoundary: boolean; showReports: boolean; showMissions: boolean; showAnimals: boolean; clusterPoints: boolean }
  reporting: { referencePrefix: string; defaultFormat: string; includeCoordinates: boolean; includePhotos: boolean }
  dataPolicy: { retentionDays: number; maskPersonalContacts: boolean; requireClosureNote: boolean }
}

const DEFAULTS: CsvrSettings = {
  shelters: [], speciesTypes: ['DOG', 'CAT', 'HORSE', 'DONKEY', 'FARM', 'OTHER'], priorityLevels: ['FAIBLE', 'NORMALE', 'HAUTE', 'URGENTE', 'SANITAIRE'], captureStates: ['CALME', 'PEUREUX', 'AGRESSIF', 'BLESSE', 'MALADE', 'AMAIGRI', 'GESTANTE', 'ALLAITANTE'],
  operational: { defaultPriority: 'NORMALE', responseTargetHours: 24, quarantineDays: 10, requireLocation: true, requirePhotoForClosure: false },
  contacts: { responsibleName: '', veterinaryService: '', emergencyPhone: '', email: '' }, notifications: { urgentAlerts: true, healthAlerts: true, missionReminders: true },
  vaccination: { preferredVaccineType: 'UNKNOWN', preferredRoute: 'UNKNOWN', protocolReference: 'WHO/OMS + البرنامج الوطني المعتمد', requireMedicalValidation: true },
  workflow: { autoCreateUrgentMission: false, followUpAfterDays: 3, lockClosedRecords: true, allowStatusReopen: false },
  map: { defaultZoom: 13, showBoundary: true, showReports: true, showMissions: true, showAnimals: true, clusterPoints: true },
  reporting: { referencePrefix: 'CSVR', defaultFormat: 'PDF', includeCoordinates: true, includePhotos: false },
  dataPolicy: { retentionDays: 3650, maskPersonalContacts: false, requireClosureNote: true },
}

const input = 'w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm outline-none focus:border-amber-400 focus:ring-2 focus:ring-amber-100'

function cloneDefaults(): CsvrSettings { return JSON.parse(JSON.stringify(DEFAULTS)) as CsvrSettings }

function Section({ icon, title, description, children }: { icon: string; title: string; description: string; children: React.ReactNode }) {
  return <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="mb-4 flex items-start gap-3"><span className="rounded-xl bg-amber-100 p-2 text-xl">{icon}</span><div><h3 className="text-sm font-extrabold text-slate-700">{title}</h3><p className="mt-1 text-xs text-slate-400">{description}</p></div></div>{children}</section>
}

function TagsEditor({ title, values, labels, onChange, placeholder }: { title: string; values: string[]; labels?: Record<string, string>; onChange: (values: string[]) => void; placeholder: string }) {
  const [value, setValue] = useState('')
  const add = () => { const next = value.trim(); if (!next || values.includes(next)) return; onChange([...values, next]); setValue('') }
  return <div><label className="mb-2 block text-xs font-bold text-slate-600">{title}</label><div className="mb-2 flex flex-wrap gap-2">{values.map((item) => <span key={item} className="inline-flex items-center gap-1 rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-bold text-slate-600">{labels?.[item] || item}<button type="button" onClick={() => onChange(values.filter((entry) => entry !== item))} className="text-slate-400 hover:text-red-600">×</button></span>)}</div><div className="flex gap-2"><input value={value} onChange={(event) => setValue(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') { event.preventDefault(); add() } }} placeholder={placeholder} className={input} /><button type="button" onClick={add} className="rounded-xl bg-slate-700 px-4 text-sm font-bold text-white">+</button></div></div>
}

export default function SettingsTab({ selectedCommune }: Props) {
  const { user } = useAppStore()
  const [settings, setSettings] = useState<CsvrSettings>(cloneDefaults())
  const [newShelter, setNewShelter] = useState<Shelter>({ name: '', address: '', capacity: 0 })
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [seedLoading, setSeedLoading] = useState(false)
  const managedCommunes = user?.managedCommunes?.length ? user.managedCommunes : (user?.commune && user.commune !== 'ALL' ? [user.commune] : [])
  const commune = selectedCommune !== 'ALL' ? selectedCommune : (managedCommunes[0] || '')
  const update = <K extends keyof CsvrSettings>(key: K, value: CsvrSettings[K]) => setSettings((current) => ({ ...current, [key]: value }))

  const load = async () => {
    if (!commune) { setLoading(false); return }
    setLoading(true)
    try { const response = await fetch(`/api/csvr/settings?commune=${encodeURIComponent(commune)}`); const data = await response.json(); if (!response.ok) throw new Error(data.error); setSettings({ ...cloneDefaults(), ...data.settings, operational: { ...DEFAULTS.operational, ...data.settings.operational }, contacts: { ...DEFAULTS.contacts, ...data.settings.contacts }, notifications: { ...DEFAULTS.notifications, ...data.settings.notifications }, vaccination: { ...DEFAULTS.vaccination, ...data.settings.vaccination }, workflow: { ...DEFAULTS.workflow, ...data.settings.workflow }, map: { ...DEFAULTS.map, ...data.settings.map }, reporting: { ...DEFAULTS.reporting, ...data.settings.reporting }, dataPolicy: { ...DEFAULTS.dataPolicy, ...data.settings.dataPolicy } }) } catch (error) { toast.error(error instanceof Error ? error.message : 'تعذر تحميل الإعدادات') } finally { setLoading(false) }
  }
  useEffect(() => { void load() }, [commune])

  const addShelter = () => { if (!newShelter.name.trim()) { toast.error('أدخل اسم المركز'); return }; update('shelters', [...settings.shelters, { ...newShelter, name: newShelter.name.trim() }]); setNewShelter({ name: '', address: '', capacity: 0 }) }
  const save = async () => { if (!commune) { toast.error('لا توجد جماعة محددة'); return }; setSaving(true); try { const response = await fetch('/api/csvr/settings', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ commune, settings }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setSettings({ ...cloneDefaults(), ...data.settings }); toast.success('تم حفظ إعدادات الحيوانات الشاردة') } catch (error) { toast.error(error instanceof Error ? error.message : 'فشل الحفظ') } finally { setSaving(false) } }
  const seed = async () => { if (!confirm('سيتم إنشاء بيانات تجريبية CSVR. هل تريد المتابعة؟')) return; setSeedLoading(true); try { const response = await fetch('/api/csvr/seed', { method: 'POST' }); const data = await response.json(); if (!response.ok) throw new Error(data.error); toast.success(`تم إنشاء ${data.created.reports} بلاغ، ${data.created.missions} مهمة، ${data.created.animals} حيوان`) } catch (error) { toast.error(error instanceof Error ? error.message : 'فشل إنشاء البيانات') } finally { setSeedLoading(false) } }

  if (loading) return <div className="flex justify-center py-16"><div className="h-9 w-9 animate-spin rounded-full border-4 border-amber-500 border-t-transparent" /></div>
  if (!commune) return <div className="py-16 text-center text-slate-400"><div className="text-4xl">⚙️</div><p className="mt-2 text-sm">يرجى تحديد جماعة الحساب</p></div>

  return <div className="space-y-4" dir="rtl">
    <div className="rounded-2xl bg-gradient-to-l from-amber-700 to-orange-500 p-5 text-white shadow-lg"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-extrabold">⚙️ إعدادات الحيوانات الشاردة</h2><p className="mt-1 text-xs text-amber-50">تهيئة دورة البلاغ، الالتقاط، الإيواء، التلقيح والتنسيق داخل نطاق الجماعة.</p></div><span className="rounded-full bg-white/15 px-3 py-1 text-xs font-bold">🏘️ {COMMUNE_LABELS[commune] || commune}</span></div></div>
    <div className="grid gap-4 lg:grid-cols-2">
      <Section icon="🎯" title="سير العمل والاستجابة" description="القيم الافتراضية التي تستعملها الفرق عند إنشاء الحالات والمهام."><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold text-slate-600">الأولوية الافتراضية<select value={settings.operational.defaultPriority} onChange={(event) => update('operational', { ...settings.operational, defaultPriority: event.target.value })} className={`${input} mt-1`}>{Object.entries(CSVR_PRIORITY_LABELS).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label className="text-xs font-bold text-slate-600">هدف الاستجابة بالساعات<input type="number" min="1" max="720" value={settings.operational.responseTargetHours} onChange={(event) => update('operational', { ...settings.operational, responseTargetHours: Number(event.target.value) || 1 })} className={`${input} mt-1`} /></label><label className="text-xs font-bold text-slate-600">مدة الحجر الافتراضية بالأيام<input type="number" min="0" max="365" value={settings.operational.quarantineDays} onChange={(event) => update('operational', { ...settings.operational, quarantineDays: Number(event.target.value) || 0 })} className={`${input} mt-1`} /></label></div><div className="mt-3 grid gap-2 sm:grid-cols-2"><label className="flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-xs font-bold text-slate-600"><input type="checkbox" checked={settings.operational.requireLocation} onChange={(event) => update('operational', { ...settings.operational, requireLocation: event.target.checked })} /> إلزام تحديد الموقع</label><label className="flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-xs font-bold text-slate-600"><input type="checkbox" checked={settings.operational.requirePhotoForClosure} onChange={(event) => update('operational', { ...settings.operational, requirePhotoForClosure: event.target.checked })} /> صورة قبل إغلاق الحالة</label></div></Section>
      <Section icon="📞" title="التنسيق والاتصال" description="بيانات المصلحة أو الطبيب البيطري التي تظهر للفريق عند الحاجة."><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold text-slate-600">المسؤول<input value={settings.contacts.responsibleName} onChange={(event) => update('contacts', { ...settings.contacts, responsibleName: event.target.value })} className={`${input} mt-1`} /></label><label className="text-xs font-bold text-slate-600">المصلحة البيطرية<input value={settings.contacts.veterinaryService} onChange={(event) => update('contacts', { ...settings.contacts, veterinaryService: event.target.value })} className={`${input} mt-1`} /></label><label className="text-xs font-bold text-slate-600">هاتف الطوارئ<input value={settings.contacts.emergencyPhone} onChange={(event) => update('contacts', { ...settings.contacts, emergencyPhone: event.target.value })} className={`${input} mt-1`} /></label><label className="text-xs font-bold text-slate-600">البريد الإلكتروني<input type="email" value={settings.contacts.email} onChange={(event) => update('contacts', { ...settings.contacts, email: event.target.value })} className={`${input} mt-1`} /></label></div></Section>
      <Section icon="🔔" title="التنبيهات" description="تحديد أنواع التنبيهات التي تستحق الظهور في لوحة اليقظة والمتابعة."><div className="grid gap-2 sm:grid-cols-3"><label className="flex items-center gap-2 rounded-xl bg-red-50 p-3 text-xs font-bold text-red-700"><input type="checkbox" checked={settings.notifications.urgentAlerts} onChange={(event) => update('notifications', { ...settings.notifications, urgentAlerts: event.target.checked })} /> الحالات العاجلة</label><label className="flex items-center gap-2 rounded-xl bg-amber-50 p-3 text-xs font-bold text-amber-700"><input type="checkbox" checked={settings.notifications.healthAlerts} onChange={(event) => update('notifications', { ...settings.notifications, healthAlerts: event.target.checked })} /> التنبيهات الصحية</label><label className="flex items-center gap-2 rounded-xl bg-blue-50 p-3 text-xs font-bold text-blue-700"><input type="checkbox" checked={settings.notifications.missionReminders} onChange={(event) => update('notifications', { ...settings.notifications, missionReminders: event.target.checked })} /> تذكير المهام</label></div></Section>
      <Section icon="🩺" title="التلقيح والوقاية" description="إعدادات توثيقية؛ اعتماد التصنيف واللقاح والبروتوكول يبقى للمرفق الصحي المختص."><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold text-slate-600">نوع اللقاح المفضل<select value={settings.vaccination.preferredVaccineType} onChange={(event) => update('vaccination', { ...settings.vaccination, preferredVaccineType: event.target.value })} className={`${input} mt-1`}>{Object.entries(RABIES_VACCINE_LABELS).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label className="text-xs font-bold text-slate-600">طريق الإعطاء المفضل<select value={settings.vaccination.preferredRoute} onChange={(event) => update('vaccination', { ...settings.vaccination, preferredRoute: event.target.value })} className={`${input} mt-1`}>{Object.entries(RABIES_ROUTE_LABELS).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label></div><input value={settings.vaccination.protocolReference} onChange={(event) => update('vaccination', { ...settings.vaccination, protocolReference: event.target.value })} placeholder="مرجع البروتوكول" className={`${input} mt-3`} /><label className="mt-3 flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-xs font-bold text-slate-600"><input type="checkbox" checked={settings.vaccination.requireMedicalValidation} onChange={(event) => update('vaccination', { ...settings.vaccination, requireMedicalValidation: event.target.checked })} /> اشتراط اعتماد المرفق الصحي قبل تغيير حالة التلقيح</label></Section>
    </div>
    <div className="grid gap-4 lg:grid-cols-2">
      <Section icon="🔄" title="قواعد دورة الحالة" description="ضبط الانتقال بين البلاغ والمهمة والمتابعة دون تنفيذ قرارات صحية تلقائية."><div className="grid gap-2 sm:grid-cols-2"><label className="flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-xs font-bold text-slate-600"><input type="checkbox" checked={settings.workflow.autoCreateUrgentMission} onChange={(event) => update('workflow', { ...settings.workflow, autoCreateUrgentMission: event.target.checked })} /> اقتراح مهمة تلقائياً للعاجل</label><label className="flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-xs font-bold text-slate-600"><input type="checkbox" checked={settings.workflow.lockClosedRecords} onChange={(event) => update('workflow', { ...settings.workflow, lockClosedRecords: event.target.checked })} /> قفل السجلات المغلقة</label><label className="flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-xs font-bold text-slate-600"><input type="checkbox" checked={settings.workflow.allowStatusReopen} onChange={(event) => update('workflow', { ...settings.workflow, allowStatusReopen: event.target.checked })} /> السماح بإعادة فتح الحالة</label><label className="text-xs font-bold text-slate-600">المتابعة بعد (أيام)<input type="number" min="0" max="90" value={settings.workflow.followUpAfterDays} onChange={(event) => update('workflow', { ...settings.workflow, followUpAfterDays: Number(event.target.value) || 0 })} className={`${input} mt-1`} /></label></div></Section>
      <Section icon="🗺️" title="إعدادات الخريطة" description="الطبقات التي تظهر افتراضياً عند فتح خريطة الحيوانات الشاردة للجماعة."><div className="grid gap-2 sm:grid-cols-2"><label className="text-xs font-bold text-slate-600">مستوى التكبير الافتراضي<input type="number" min="5" max="19" value={settings.map.defaultZoom} onChange={(event) => update('map', { ...settings.map, defaultZoom: Number(event.target.value) || 13 })} className={`${input} mt-1`} /></label><label className="flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-xs font-bold text-slate-600"><input type="checkbox" checked={settings.map.clusterPoints} onChange={(event) => update('map', { ...settings.map, clusterPoints: event.target.checked })} /> تجميع النقاط المتقاربة</label>{[['showBoundary', 'حدود الجماعة'], ['showReports', 'بلاغات المواطنين'], ['showMissions', 'المهام الميدانية'], ['showAnimals', 'الحيوانات المسجلة']].map(([key, label]) => <label key={key} className="flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-xs font-bold text-slate-600"><input type="checkbox" checked={settings.map[key as keyof typeof settings.map] as boolean} onChange={(event) => update('map', { ...settings.map, [key]: event.target.checked })} /> {label}</label>)}</div></Section>
      <Section icon="📄" title="التقارير والترقيم" description="توحيد مراجع التقارير ومحتوى المعاينة والتصدير للقسم."><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold text-slate-600">بادئة المرجع<input value={settings.reporting.referencePrefix} onChange={(event) => update('reporting', { ...settings.reporting, referencePrefix: event.target.value })} className={`${input} mt-1`} /></label><label className="text-xs font-bold text-slate-600">الصيغة الافتراضية<select value={settings.reporting.defaultFormat} onChange={(event) => update('reporting', { ...settings.reporting, defaultFormat: event.target.value })} className={`${input} mt-1`}><option value="PDF">PDF</option><option value="CSV">CSV / Excel</option><option value="JSON">JSON</option></select></label></div><div className="mt-3 grid gap-2 sm:grid-cols-2"><label className="flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-xs font-bold text-slate-600"><input type="checkbox" checked={settings.reporting.includeCoordinates} onChange={(event) => update('reporting', { ...settings.reporting, includeCoordinates: event.target.checked })} /> تضمين الإحداثيات</label><label className="flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-xs font-bold text-slate-600"><input type="checkbox" checked={settings.reporting.includePhotos} onChange={(event) => update('reporting', { ...settings.reporting, includePhotos: event.target.checked })} /> تضمين روابط الصور</label></div></Section>
      <Section icon="🔐" title="حماية واحتفاظ البيانات" description="تقليل الوصول غير الضروري وتنظيم مدة الاحتفاظ الإداري بالسجلات."><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold text-slate-600">الاحتفاظ بالسجلات (أيام)<input type="number" min="30" max="36500" value={settings.dataPolicy.retentionDays} onChange={(event) => update('dataPolicy', { ...settings.dataPolicy, retentionDays: Number(event.target.value) || 30 })} className={`${input} mt-1`} /></label><label className="flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-xs font-bold text-slate-600"><input type="checkbox" checked={settings.dataPolicy.maskPersonalContacts} onChange={(event) => update('dataPolicy', { ...settings.dataPolicy, maskPersonalContacts: event.target.checked })} /> إخفاء أرقام الاتصال في العرض</label><label className="flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-xs font-bold text-slate-600 sm:col-span-2"><input type="checkbox" checked={settings.dataPolicy.requireClosureNote} onChange={(event) => update('dataPolicy', { ...settings.dataPolicy, requireClosureNote: event.target.checked })} /> اشتراط ملاحظة قبل إغلاق الحالة</label></div></Section>
    </div>
    <Section icon="🧩" title="القوائم القابلة للتهيئة" description="أضف أو احذف القيم التي تظهر في النماذج دون تعديل الكود."><div className="grid gap-5 lg:grid-cols-3"><TagsEditor title="أنواع الحيوانات" values={settings.speciesTypes} onChange={(values) => update('speciesTypes', values)} placeholder="DOG أو نوع جديد" /><TagsEditor title="حالات الالتقاط" values={settings.captureStates} labels={CSVR_CAPTURE_STATE_LABELS} onChange={(values) => update('captureStates', values)} placeholder="حالة جديدة" /><TagsEditor title="مستويات الأولوية" values={settings.priorityLevels} labels={CSVR_PRIORITY_LABELS} onChange={(values) => update('priorityLevels', values)} placeholder="أولوية جديدة" /></div></Section>
    <Section icon="🏠" title="مراكز الاستقبال والإيواء" description="إدارة المراكز التي يمكن ربطها بعمليات الإيواء والنقل داخل الجماعة."><div className="space-y-2">{settings.shelters.length === 0 && <p className="py-3 text-center text-xs text-slate-400">لا توجد مراكز مسجلة.</p>}{settings.shelters.map((shelter, index) => <motion.div key={`${shelter.name}-${index}`} initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="flex flex-wrap items-center gap-3 rounded-xl bg-slate-50 p-3"><span className="text-lg">🏠</span><div className="min-w-[180px] flex-1"><strong className="text-sm text-slate-700">{shelter.name}</strong><p className="text-[11px] text-slate-400">{shelter.address || 'دون عنوان'} · السعة {shelter.capacity}</p></div><button type="button" onClick={() => update('shelters', settings.shelters.filter((_, itemIndex) => itemIndex !== index))} className="text-xs font-bold text-red-600">حذف</button></motion.div>)}</div><div className="mt-4 grid gap-2 border-t border-slate-100 pt-4 sm:grid-cols-[1fr_1fr_130px_auto]"><input value={newShelter.name} onChange={(event) => setNewShelter({ ...newShelter, name: event.target.value })} placeholder="اسم المركز" className={input} /><input value={newShelter.address} onChange={(event) => setNewShelter({ ...newShelter, address: event.target.value })} placeholder="العنوان" className={input} /><input type="number" min="0" value={newShelter.capacity || ''} onChange={(event) => setNewShelter({ ...newShelter, capacity: Number(event.target.value) || 0 })} placeholder="السعة" className={input} /><button type="button" onClick={addShelter} className="rounded-xl bg-slate-700 px-4 py-2 text-sm font-bold text-white">إضافة</button></div></Section>
    <div className="flex flex-wrap items-center justify-between gap-3"><button type="button" onClick={save} disabled={saving} className="rounded-xl bg-amber-600 px-6 py-3 text-sm font-extrabold text-white shadow-sm hover:bg-amber-700 disabled:opacity-50">{saving ? 'جارٍ الحفظ...' : '💾 حفظ إعدادات الجماعة'}</button>{user?.role === 'admin' && <button type="button" onClick={seed} disabled={seedLoading} className="rounded-xl border border-blue-200 bg-blue-50 px-4 py-3 text-xs font-bold text-blue-700">{seedLoading ? 'جارٍ الإنشاء...' : '🌱 إنشاء بيانات تجريبية'}</button>}</div>
  </div>
}
