'use client'

import React, { useEffect, useState } from 'react'
import { motion } from 'framer-motion'
import { toast } from 'sonner'
import { useAppStore } from '@/lib/store'
import { COMMUNE_LABELS } from '@/lib/constants'

interface Props { selectedCommune: string }

interface EnvironmentSettings {
  categories: string[]
  pollutionTypes: string[]
  wasteTypes: string[]
  siteTypes: string[]
  operational: { defaultPriority: string; responseTargetHours: number; followUpAfterDays: number; requireLocation: boolean; requirePhotoForClosure: boolean }
  contacts: { responsibleName: string; serviceName: string; emergencyPhone: string; email: string }
  notifications: { urgentAlerts: boolean; pollutionAlerts: boolean; inspectionReminders: boolean; campaignReminders: boolean }
  workflow: { autoCreateInspection: boolean; lockClosedRecords: boolean; allowStatusReopen: boolean; requireClosureNote: boolean }
  map: { defaultZoom: number; showBoundary: boolean; showDossiers: boolean; showPollution: boolean; showWaste: boolean; showSites: boolean; clusterPoints: boolean }
  reporting: { referencePrefix: string; defaultFormat: string; includeCoordinates: boolean; includePhotos: boolean; includeRiskSummary: boolean }
  dataPolicy: { retentionDays: number; maskPersonalContacts: boolean; requireEvidenceForClosure: boolean }
}

const DEFAULTS: EnvironmentSettings = {
  categories: ['POLLUTION', 'WASTE', 'NATURAL_SITE', 'ESTABLISHMENT', 'COMPLAINT', 'PROGRAM'],
  pollutionTypes: ['AIR', 'WATER', 'SOIL', 'NOISE', 'ODOR', 'OTHER'],
  wasteTypes: ['HOUSEHOLD', 'CONSTRUCTION', 'GREEN', 'DANGEROUS', 'OTHER'],
  siteTypes: ['FOREST', 'WETLAND', 'COAST', 'PARK', 'WATERCOURSE', 'OTHER'],
  operational: { defaultPriority: 'NORMALE', responseTargetHours: 48, followUpAfterDays: 7, requireLocation: true, requirePhotoForClosure: true },
  contacts: { responsibleName: '', serviceName: 'مصلحة المحافظة على البيئة', emergencyPhone: '', email: '' },
  notifications: { urgentAlerts: true, pollutionAlerts: true, inspectionReminders: true, campaignReminders: true },
  workflow: { autoCreateInspection: false, lockClosedRecords: true, allowStatusReopen: false, requireClosureNote: true },
  map: { defaultZoom: 13, showBoundary: true, showDossiers: true, showPollution: true, showWaste: true, showSites: true, clusterPoints: true },
  reporting: { referencePrefix: 'ENV', defaultFormat: 'PDF', includeCoordinates: true, includePhotos: true, includeRiskSummary: true },
  dataPolicy: { retentionDays: 3650, maskPersonalContacts: false, requireEvidenceForClosure: true },
}

const input = 'w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm outline-none focus:border-amber-400 focus:ring-2 focus:ring-amber-100'

function cloneDefaults() { return JSON.parse(JSON.stringify(DEFAULTS)) as EnvironmentSettings }

function Section({ icon, title, description, children }: { icon: string; title: string; description: string; children: React.ReactNode }) {
  return <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="mb-4 flex items-start gap-3"><span className="rounded-xl bg-amber-100 p-2 text-xl">{icon}</span><div><h3 className="text-sm font-extrabold text-slate-700">{title}</h3><p className="mt-1 text-xs text-slate-400">{description}</p></div></div>{children}</section>
}

function TagsEditor({ title, values, onChange, placeholder }: { title: string; values: string[]; onChange: (values: string[]) => void; placeholder: string }) {
  const [value, setValue] = useState('')
  const add = () => { const next = value.trim(); if (!next || values.includes(next)) return; onChange([...values, next]); setValue('') }
  return <div><label className="mb-2 block text-xs font-bold text-slate-600">{title}</label><div className="mb-2 flex flex-wrap gap-2">{values.map((item) => <span key={item} className="inline-flex items-center gap-1 rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-bold text-slate-600">{item}<button type="button" onClick={() => onChange(values.filter((entry) => entry !== item))} className="text-slate-400 hover:text-red-600">×</button></span>)}</div><div className="flex gap-2"><input value={value} onChange={(event) => setValue(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') { event.preventDefault(); add() } }} placeholder={placeholder} className={input} /><button type="button" onClick={add} className="rounded-xl bg-slate-700 px-4 text-sm font-bold text-white">+</button></div></div>
}

export default function EnvironmentSettingsTab({ selectedCommune }: Props) {
  const { user } = useAppStore()
  const [settings, setSettings] = useState<EnvironmentSettings>(cloneDefaults())
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const managedCommunes = user?.managedCommunes?.length ? user.managedCommunes : (user?.commune && user.commune !== 'ALL' ? [user.commune] : [])
  const commune = selectedCommune !== 'ALL' ? selectedCommune : (managedCommunes[0] || '')
  const update = <K extends keyof EnvironmentSettings>(key: K, value: EnvironmentSettings[K]) => setSettings((current) => ({ ...current, [key]: value }))

  useEffect(() => {
    if (!commune) { setLoading(false); return }
    setLoading(true)
    fetch(`/api/environment/settings?commune=${encodeURIComponent(commune)}`).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error); setSettings({ ...cloneDefaults(), ...data.settings, operational: { ...DEFAULTS.operational, ...data.settings.operational }, contacts: { ...DEFAULTS.contacts, ...data.settings.contacts }, notifications: { ...DEFAULTS.notifications, ...data.settings.notifications }, workflow: { ...DEFAULTS.workflow, ...data.settings.workflow }, map: { ...DEFAULTS.map, ...data.settings.map }, reporting: { ...DEFAULTS.reporting, ...data.settings.reporting }, dataPolicy: { ...DEFAULTS.dataPolicy, ...data.settings.dataPolicy } }) }).catch((error) => toast.error(error instanceof Error ? error.message : 'تعذر تحميل الإعدادات')).finally(() => setLoading(false))
  }, [commune])

  const save = async () => {
    if (!commune) { toast.error('يرجى تحديد جماعة الحساب'); return }
    setSaving(true)
    try { const response = await fetch('/api/environment/settings', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ commune, settings }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setSettings({ ...cloneDefaults(), ...data.settings }); toast.success('تم حفظ إعدادات المحافظة على البيئة') } catch (error) { toast.error(error instanceof Error ? error.message : 'فشل حفظ الإعدادات') } finally { setSaving(false) }
  }

  if (loading) return <div className="flex justify-center py-16"><div className="h-9 w-9 animate-spin rounded-full border-4 border-amber-500 border-t-transparent" /></div>
  if (!commune) return <div className="py-16 text-center text-slate-400"><div className="text-4xl">⚙️</div><p className="mt-2 text-sm">يرجى تحديد جماعة الحساب</p></div>

  return <div className="space-y-4" dir="rtl">
    <div className="rounded-2xl bg-gradient-to-l from-amber-700 to-orange-500 p-5 text-white shadow-lg"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-extrabold">⚙️ إعدادات المحافظة على البيئة</h2><p className="mt-1 text-xs text-amber-50">تهيئة دورة الملفات البيئية، المعاينات، التلوث، النفايات، المواقع والتقارير داخل نطاق الجماعة.</p></div><span className="rounded-full bg-white/15 px-3 py-1 text-xs font-bold">🏘️ {COMMUNE_LABELS[commune] || commune}</span></div></div>
    <div className="grid gap-4 lg:grid-cols-2">
      <Section icon="🎯" title="سير العمل والاستجابة" description="القيم الافتراضية للملفات والمعاينات البيئية."><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold text-slate-600">الأولوية الافتراضية<select value={settings.operational.defaultPriority} onChange={(event) => update('operational', { ...settings.operational, defaultPriority: event.target.value })} className={`${input} mt-1`}><option value="FAIBLE">منخفضة</option><option value="NORMALE">عادية</option><option value="HAUTE">عالية</option><option value="URGENTE">عاجلة</option></select></label><label className="text-xs font-bold text-slate-600">هدف الاستجابة بالساعات<input type="number" min="1" max="720" value={settings.operational.responseTargetHours} onChange={(event) => update('operational', { ...settings.operational, responseTargetHours: Number(event.target.value) || 1 })} className={`${input} mt-1`} /></label><label className="text-xs font-bold text-slate-600">المتابعة بعد (أيام)<input type="number" min="0" max="365" value={settings.operational.followUpAfterDays} onChange={(event) => update('operational', { ...settings.operational, followUpAfterDays: Number(event.target.value) || 0 })} className={`${input} mt-1`} /></label></div><div className="mt-3 grid gap-2 sm:grid-cols-2"><label className="flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-xs font-bold text-slate-600"><input type="checkbox" checked={settings.operational.requireLocation} onChange={(event) => update('operational', { ...settings.operational, requireLocation: event.target.checked })} /> إلزام تحديد الموقع</label><label className="flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-xs font-bold text-slate-600"><input type="checkbox" checked={settings.operational.requirePhotoForClosure} onChange={(event) => update('operational', { ...settings.operational, requirePhotoForClosure: event.target.checked })} /> دليل قبل الإغلاق</label></div></Section>
      <Section icon="📞" title="التنسيق والاتصال" description="بيانات المصلحة التي تظهر للفريق عند الحاجة."><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold text-slate-600">المسؤول<input value={settings.contacts.responsibleName} onChange={(event) => update('contacts', { ...settings.contacts, responsibleName: event.target.value })} className={`${input} mt-1`} /></label><label className="text-xs font-bold text-slate-600">اسم المصلحة<input value={settings.contacts.serviceName} onChange={(event) => update('contacts', { ...settings.contacts, serviceName: event.target.value })} className={`${input} mt-1`} /></label><label className="text-xs font-bold text-slate-600">هاتف الطوارئ<input value={settings.contacts.emergencyPhone} onChange={(event) => update('contacts', { ...settings.contacts, emergencyPhone: event.target.value })} className={`${input} mt-1`} /></label><label className="text-xs font-bold text-slate-600">البريد الإلكتروني<input type="email" value={settings.contacts.email} onChange={(event) => update('contacts', { ...settings.contacts, email: event.target.value })} className={`${input} mt-1`} /></label></div></Section>
      <Section icon="🔔" title="التنبيهات" description="تفعيل التنبيهات التشغيلية حسب نوع الملف البيئي."><div className="grid gap-2 sm:grid-cols-2"><label className="flex items-center gap-2 rounded-xl bg-red-50 p-3 text-xs font-bold text-red-700"><input type="checkbox" checked={settings.notifications.urgentAlerts} onChange={(event) => update('notifications', { ...settings.notifications, urgentAlerts: event.target.checked })} /> الحالات العاجلة</label><label className="flex items-center gap-2 rounded-xl bg-amber-50 p-3 text-xs font-bold text-amber-700"><input type="checkbox" checked={settings.notifications.pollutionAlerts} onChange={(event) => update('notifications', { ...settings.notifications, pollutionAlerts: event.target.checked })} /> حوادث التلوث</label><label className="flex items-center gap-2 rounded-xl bg-blue-50 p-3 text-xs font-bold text-blue-700"><input type="checkbox" checked={settings.notifications.inspectionReminders} onChange={(event) => update('notifications', { ...settings.notifications, inspectionReminders: event.target.checked })} /> تذكير المعاينات</label><label className="flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-xs font-bold text-slate-600"><input type="checkbox" checked={settings.notifications.campaignReminders} onChange={(event) => update('notifications', { ...settings.notifications, campaignReminders: event.target.checked })} /> الحملات التحسيسية</label></div></Section>
      <Section icon="🔄" title="قواعد دورة الملف" description="ضبط الانتقال بين الملف والمعاينة والمتابعة مع إبقاء القرار الإداري بيد الموظف المختص."><div className="grid gap-2 sm:grid-cols-2"><label className="flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-xs font-bold text-slate-600"><input type="checkbox" checked={settings.workflow.autoCreateInspection} onChange={(event) => update('workflow', { ...settings.workflow, autoCreateInspection: event.target.checked })} /> اقتراح معاينة تلقائياً</label><label className="flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-xs font-bold text-slate-600"><input type="checkbox" checked={settings.workflow.lockClosedRecords} onChange={(event) => update('workflow', { ...settings.workflow, lockClosedRecords: event.target.checked })} /> قفل الملفات المغلقة</label><label className="flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-xs font-bold text-slate-600"><input type="checkbox" checked={settings.workflow.allowStatusReopen} onChange={(event) => update('workflow', { ...settings.workflow, allowStatusReopen: event.target.checked })} /> السماح بإعادة الفتح</label><label className="flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-xs font-bold text-slate-600"><input type="checkbox" checked={settings.workflow.requireClosureNote} onChange={(event) => update('workflow', { ...settings.workflow, requireClosureNote: event.target.checked })} /> ملاحظة عند الإغلاق</label></div></Section>
    </div>
    <div className="grid gap-4 lg:grid-cols-2">
      <Section icon="🗺️" title="إعدادات الخريطة" description="الطبقات الافتراضية عند فتح خريطة البيئة للجماعة."><div className="grid gap-2 sm:grid-cols-2"><label className="text-xs font-bold text-slate-600">مستوى التكبير<input type="number" min="5" max="19" value={settings.map.defaultZoom} onChange={(event) => update('map', { ...settings.map, defaultZoom: Number(event.target.value) || 13 })} className={`${input} mt-1`} /></label><label className="flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-xs font-bold text-slate-600"><input type="checkbox" checked={settings.map.clusterPoints} onChange={(event) => update('map', { ...settings.map, clusterPoints: event.target.checked })} /> تجميع النقاط</label>{[['showBoundary', 'حدود الجماعة'], ['showDossiers', 'الملفات البيئية'], ['showPollution', 'حوادث التلوث'], ['showWaste', 'النفايات'], ['showSites', 'المواقع الطبيعية']].map(([key, label]) => <label key={key} className="flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-xs font-bold text-slate-600"><input type="checkbox" checked={settings.map[key as keyof typeof settings.map] as boolean} onChange={(event) => update('map', { ...settings.map, [key]: event.target.checked })} /> {label}</label>)}</div></Section>
      <Section icon="📄" title="التقارير والقوالب" description="توحيد المراجع والمعاينة ومحتوى التصدير في جميع وثائق القسم."><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold text-slate-600">بادئة المرجع<input value={settings.reporting.referencePrefix} onChange={(event) => update('reporting', { ...settings.reporting, referencePrefix: event.target.value })} className={`${input} mt-1`} /></label><label className="text-xs font-bold text-slate-600">الصيغة الافتراضية<select value={settings.reporting.defaultFormat} onChange={(event) => update('reporting', { ...settings.reporting, defaultFormat: event.target.value })} className={`${input} mt-1`}><option value="PDF">PDF</option><option value="CSV">CSV / Excel</option><option value="JSON">JSON</option></select></label></div><div className="mt-3 grid gap-2 sm:grid-cols-3"><label className="flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-xs font-bold text-slate-600"><input type="checkbox" checked={settings.reporting.includeCoordinates} onChange={(event) => update('reporting', { ...settings.reporting, includeCoordinates: event.target.checked })} /> الإحداثيات</label><label className="flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-xs font-bold text-slate-600"><input type="checkbox" checked={settings.reporting.includePhotos} onChange={(event) => update('reporting', { ...settings.reporting, includePhotos: event.target.checked })} /> الصور</label><label className="flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-xs font-bold text-slate-600"><input type="checkbox" checked={settings.reporting.includeRiskSummary} onChange={(event) => update('reporting', { ...settings.reporting, includeRiskSummary: event.target.checked })} /> ملخص الخطر</label></div></Section>
      <Section icon="🛡️" title="حماية البيانات" description="ضبط مدة الاحتفاظ والحد الأدنى من بيانات الاتصال الظاهرة."><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold text-slate-600">الاحتفاظ بالسجلات (أيام)<input type="number" min="30" max="36500" value={settings.dataPolicy.retentionDays} onChange={(event) => update('dataPolicy', { ...settings.dataPolicy, retentionDays: Number(event.target.value) || 30 })} className={`${input} mt-1`} /></label><label className="flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-xs font-bold text-slate-600"><input type="checkbox" checked={settings.dataPolicy.maskPersonalContacts} onChange={(event) => update('dataPolicy', { ...settings.dataPolicy, maskPersonalContacts: event.target.checked })} /> إخفاء أرقام الاتصال</label><label className="flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-xs font-bold text-slate-600 sm:col-span-2"><input type="checkbox" checked={settings.dataPolicy.requireEvidenceForClosure} onChange={(event) => update('dataPolicy', { ...settings.dataPolicy, requireEvidenceForClosure: event.target.checked })} /> اشتراط دليل قبل إغلاق الملف</label></div></Section>
    </div>
    <Section icon="🧩" title="القوائم القابلة للتهيئة" description="أضف أو احذف القيم التي تظهر في نماذج القسم دون تعديل الكود."><div className="grid gap-5 lg:grid-cols-2"><TagsEditor title="فئات الملفات" values={settings.categories} onChange={(values) => update('categories', values)} placeholder="فئة جديدة" /><TagsEditor title="أنواع التلوث" values={settings.pollutionTypes} onChange={(values) => update('pollutionTypes', values)} placeholder="نوع تلوث جديد" /><TagsEditor title="أنواع النفايات" values={settings.wasteTypes} onChange={(values) => update('wasteTypes', values)} placeholder="نوع نفايات جديد" /><TagsEditor title="أنواع المواقع الطبيعية" values={settings.siteTypes} onChange={(values) => update('siteTypes', values)} placeholder="نوع موقع جديد" /></div></Section>
    <div className="flex justify-end"><button type="button" onClick={save} disabled={saving} className="rounded-xl bg-amber-600 px-6 py-3 text-sm font-extrabold text-white shadow-sm hover:bg-amber-700 disabled:opacity-50">{saving ? 'جارٍ الحفظ...' : '💾 حفظ إعدادات الجماعة'}</button></div>
  </div>
}
